create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  round_no integer not null,
  main_numbers integer[] not null,
  bonus_number integer not null,
  sum_total integer not null,
  even_count integer not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.lotto_draws enable row level security;

create policy "Allow public insert on lotto_draws"
on public.lotto_draws
for insert
to anon
with check (true);
